# 이것까지 Git에 넣었어야 '그냥' 됩니다!
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin-binding
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# 이 밑에 원래 있던 Deployment와 Service가 오는 거죠!

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      # 아까 만든 권한(ServiceAccount)을 연결해줍니다.
      serviceAccountName: jenkins-admin 
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        securityContext:
          runAsUser: 0  # 권한 문제를 방지하기 위해 root로 실행 (연습용)
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001  # 브라우저 접속용 포트
